# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20180214_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='host_lc',
            field=models.CharField(choices=[('6TH OCTOBER', '6TH OCTOBER'), ('AAST Alexandria', 'AAST Alexandria'), ('AAST In CAIRO', 'AAST In CAIRO'), ('Ain Shams University', 'Ain Shams University'), ('Alexandria', 'Alexandria'), ('Assiut', 'Assiut'), ('Beni Suef', 'Beni Suef'), ('Cairo University', 'Cairo University'), ('Damietta', 'Damietta'), ('Fayoum', 'Fayoum'), ('GUC', 'GUC'), ('Helwan', 'Helwan'), ('Luxor & Aswan', 'Luxor & Aswan'), ('Mansoura', 'Mansoura'), ('Menofia', 'Menofia'), ('Minya', 'Minya'), ('MIU', 'MIU'), ('New Cairo', 'New Cairo'), ('Sohag', 'Sohag'), ('Suez', 'Suez'), ('Tanta', 'Tanta'), ('Zagazig', 'Zagazig')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='program',
            field=models.CharField(choices=[('GV', 'Global Volunteer'), ('GE', 'Global Entrepreneur'), ('GT', 'Global Talent')], max_length=1, null=True),
        ),
    ]
