# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Token',
            },
        ),
        migrations.AddField(
            model_name='office',
            name='entity_type',
            field=models.CharField(choices=[('AI', 'AIESEC INTERNATIONAL'), ('RE', 'Regional'), ('MC', 'Members Committee'), ('LC', 'Local Committee'), ('XX', 'Type Unknown')], default='XX', max_length=2),
        ),
        migrations.AddField(
            model_name='office',
            name='parent_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Office'),
        ),
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
