# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180225_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.RemoveField(
            model_name='office',
            name='parent_office',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
