# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180423_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.OneToOneField(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserSector'),
        ),
    ]
