# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180423_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserSector'),
        ),
    ]
