# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180423_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.BigIntegerField(blank=True, help_text='Enter the number with country code.', null=True),
        ),
    ]
