# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='uploads/'),
        ),
    ]
