# Generated by Django 2.0 on 2018-07-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180602_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
