# Generated by Django 2.0 on 2018-06-13 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_name', models.CharField(blank=True, help_text='Enter Your Full Name.', max_length=128, null=True)),
                ('ep_number', models.BigIntegerField(blank=True, help_text='Enter the number with country code.', null=True)),
                ('ep_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ep_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('ep_expa_id', models.IntegerField(blank=True, help_text='Enter EP ID.', null=True)),
                ('opp_id', models.IntegerField(blank=True, help_text='Enter Opportunity ID.', null=True)),
                ('ep_lc', models.CharField(blank=True, help_text='Enter lc Name.', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler_name', models.CharField(blank=True, help_text='Enter Your Full Name.', max_length=128, null=True)),
                ('filler_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('office_id', models.IntegerField(blank=True, null=True)),
                ('office_contact_name', models.CharField(blank=True, max_length=128, null=True)),
                ('office_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_contact_phone', models.BigIntegerField(blank=True, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_state', models.CharField(blank=True, choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=128, null=True)),
                ('process_type', models.CharField(blank=True, max_length=128, null=True)),
                ('set_ecb_responsible', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, help_text='Detailed yet to the point!', null=True)),
                ('choose_standards', models.BooleanField(default=False)),
                ('contacted_host', models.BooleanField(default=False)),
                ('host_contact_output', models.TextField(blank=True, help_text='Detailed yet to the point!', null=True)),
                ('contacted_ep', models.BooleanField(default=False)),
                ('ep_contact_output', models.TextField(blank=True, help_text='Detailed yet to the point!', null=True)),
                ('complaint_state', models.CharField(blank=True, choices=[('Solved', 'Solved'), ('Not Solved', 'Not Solved')], max_length=128, null=True)),
                ('sent_to_icb', models.BooleanField(default=False)),
                ('request_state', models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Not Confirmed', 'Not Confirmed')], max_length=128, null=True)),
                ('action_taken', models.TextField(blank=True, help_text='Detailed yet to the point!', null=True)),
                ('icb_escalated', models.BooleanField(default=False)),
                ('oca_file', models.FileField(upload_to='uploads/process_files/oca')),
                ('case_result', models.FileField(upload_to='uploads/process_files/case_result')),
                ('outcome', models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost')], max_length=128, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=128, null=True)),
                ('invoice', models.FileField(upload_to='uploads/process_files/invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=128, null=True)),
                ('ticket_state', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=128, null=True)),
                ('program', models.CharField(blank=True, choices=[('1', 'Global Volunteer'), ('2', 'Global Talent'), ('5', 'Global Entrepreneur')], max_length=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.TextField(blank=True, help_text='Detailed yet to the point for us to help you best!', null=True)),
                ('complaint_type', models.CharField(blank=True, max_length=128, null=True)),
                ('complaint_tag', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Accomodation', 'Accomodation'), ('Job Description', 'Job Description'), ('Other', 'Other')], max_length=128, null=True)),
                ('complaint_solution', models.TextField(blank=True, null=True)),
                ('requested_break', models.CharField(blank=True, choices=[('Approval', 'Approval'), ('Realization', 'Realization')], max_length=128, null=True)),
                ('request_Reason', models.TextField(blank=True, help_text='Detailed yet to the point for us to help you best!', null=True)),
                ('case_mail_subject', models.CharField(blank=True, max_length=128, null=True)),
                ('case_brief', models.TextField(blank=True, help_text='Detailed yet to the point', null=True)),
                ('ecb_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ep', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Ep')),
                ('filler', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Filler')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Office')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Process')),
                ('standards', models.ManyToManyField(blank=True, to='forms.Standard')),
            ],
        ),
        migrations.AddField(
            model_name='filler',
            name='filler_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Office'),
        ),
        migrations.AddField(
            model_name='filler',
            name='filler_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Position'),
        ),
        migrations.AddField(
            model_name='filler',
            name='filler_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Role'),
        ),
        migrations.AddField(
            model_name='ep',
            name='ep_host_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Office'),
        ),
    ]
