# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_name', models.CharField(help_text='Enter Your Full Name.', max_length=128)),
                ('ep_number', models.BigIntegerField(help_text='Enter the number with country code.')),
                ('ep_email', models.EmailField(max_length=254)),
                ('ep_country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('ep_expa_id', models.IntegerField(help_text='Enter EP ID.')),
                ('opp_id', models.IntegerField(help_text='Enter Opportunity ID.')),
            ],
        ),
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler_name', models.CharField(blank=True, help_text='Enter Your Full Name.', max_length=128, null=True)),
                ('filler_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=128, null=True)),
                ('ticket_state', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('program', models.CharField(choices=[('1', 'Global Volunteer'), ('2', 'Global Talent'), ('5', 'Global Entrepreneur')], max_length=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.TextField(help_text='Detailed yet to the point for us to help you best!', null=True)),
                ('complaint_type', models.CharField(max_length=128, null=True)),
                ('complaint_tag', multiselectfield.db.fields.MultiSelectField(choices=[('Accomodation', 'Accomodation'), ('Job Description', 'Job Description'), ('Other', 'Other')], max_length=128, null=True)),
                ('complaint_solution', models.TextField()),
                ('requested_break', models.CharField(choices=[('Approval', 'Approval'), ('Realization', 'Realization')], max_length=1, null=True)),
                ('request_Reason', models.TextField(help_text='Detailed yet to the point for us to help you best!', null=True)),
                ('ep', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Ep')),
            ],
        ),
        migrations.AddField(
            model_name='filler',
            name='Filler_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Offices'),
        ),
        migrations.AddField(
            model_name='filler',
            name='filler_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Position'),
        ),
        migrations.AddField(
            model_name='filler',
            name='filler_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Role'),
        ),
        migrations.AddField(
            model_name='ep',
            name='ep_host_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Offices'),
        ),
    ]
