# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ep',
            name='ep_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ep',
            name='ep_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ep',
            name='ep_expa_id',
            field=models.IntegerField(blank=True, help_text='Enter EP ID.', null=True),
        ),
        migrations.AlterField(
            model_name='ep',
            name='ep_name',
            field=models.CharField(blank=True, help_text='Enter Your Full Name.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ep',
            name='ep_number',
            field=models.BigIntegerField(blank=True, help_text='Enter the number with country code.', null=True),
        ),
        migrations.AlterField(
            model_name='ep',
            name='opp_id',
            field=models.IntegerField(blank=True, help_text='Enter Opportunity ID.', null=True),
        ),
    ]
