# Generated by Django 2.0 on 2018-08-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='process',
        ),
        migrations.AddField(
            model_name='ticket',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Detailed yet to the point!', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='case_result',
            field=models.FileField(null=True, upload_to='uploads/process_files/case_result'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='choose_standards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='complaint_state',
            field=models.CharField(blank=True, choices=[('Solved', 'Solved'), ('Not Solved', 'Not Solved')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contacted_ep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contacted_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='currency',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ep_contact_output',
            field=models.TextField(blank=True, help_text='Detailed yet to the point!', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='host_contact_output',
            field=models.TextField(blank=True, help_text='Detailed yet to the point!', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='icb_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='invoice',
            field=models.FileField(null=True, upload_to='uploads/process_files/invoice'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='oca_file',
            field=models.FileField(null=True, upload_to='uploads/process_files/oca'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='outcome_reason',
            field=models.TextField(blank=True, help_text='Detailed yet to the point!', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='request_state',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Not Confirmed', 'Not Confirmed')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sent_to_icb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='set_ecb_responsible',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
