# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint',
            field=models.TextField(default=None, help_text='Detailed yet to the point for us to help you best!'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='host_lc',
            field=models.CharField(choices=[('6TH OCTOBER', '6TH OCTOBER'), ('AAST Alexandria', 'AAST Alexandria'), ('AAST In CAIRO', 'AAST In CAIRO'), ('Ain Shams University', 'Ain Shams University'), ('Alexandria', 'Alexandria'), ('Assiut', 'Assiut'), ('Beni Suef', 'Beni Suef'), ('Cairo University', 'Cairo University'), ('Damietta', 'Damietta'), ('Fayoum', 'Fayoum'), ('GUC', 'GUC'), ('Helwan', 'Helwan'), ('Luxor & Aswan', 'Luxor & Aswan'), ('Mansoura', 'Mansoura'), ('Menofia', 'Menofia'), ('Minya', 'Minya'), ('MIU', 'MIU'), ('New Cairo', 'New Cairo'), ('Sohag', 'Sohag'), ('Suez', 'Suez'), ('Tanta', 'Tanta'), ('Zagazig', 'Zagazig')], help_text='Choose the host LC name.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='program',
            field=models.CharField(choices=[('GV', 'Global Volunteer'), ('GE', 'Global Entrepreneur'), ('GT', 'Global Talent')], help_text='Choose the one you are in', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='whatsapp_number',
            field=models.BigIntegerField(default=None, help_text='Enter the number with country code.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='full_name',
            field=models.CharField(default=None, help_text='Enter Your Full Name.', max_length=128),
            preserve_default=False,
        ),
    ]
