# Generated by Django 2.0 on 2018-08-13 16:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20180813_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='complaint_tag',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='standards',
        ),
        migrations.AddField(
            model_name='ticket',
            name='standards',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Personal Goal Setting', '1'), ('Outgoing Preparation Seminar', '2'), ('Expectation Setting', '3'), ('Incoming Preparation Seminar', '4'), ('Development Spaces', '5'), ('Debrief With AIESEC Home', '6'), ('Visa And Work Permit Information', '7'), ('Arrival Pickup', '8'), ('Departure Support', '9'), ('Job Description Information', '10'), ('Duration', '11'), ('Working Hours', '12'), ('First Day of Work', '13'), ('Insurance', '14'), ('Accommodation', '15'), ('Basic Living Cost', '16')], max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
