# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 18:31
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20180214_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Accomodation', 'Accomodation'), ('Job Description', 'Job Description'), ('Other', 'Other')], max_length=1, null=True),
        ),
    ]
