# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20180420_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requested_break',
            field=models.CharField(choices=[('Approval', 'Approval'), ('Realization', 'Realization')], max_length=128, null=True),
        ),
    ]
