# Generated by Django 2.0 on 2018-08-13 17:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20180813_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='case_result',
            field=models.FileField(blank=True, null=True, upload_to='uploads/process_files/case_result'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='uploads/process_files/invoice'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='oca_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/process_files/oca'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='standards',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('#1', 'Personal Goal Setting'), ('#2', 'Outgoing Preparation Seminar'), ('#3', 'Expectation Setting'), ('#4', 'Incoming Preparation Seminar'), ('#5', 'Development Spaces'), ('#6', 'Debrief With AIESEC Home'), ('#7', 'Visa And Work Permit Information'), ('#8', 'Arrival Pickup'), ('#9', 'Departure Support'), ('#10', 'Job Description Information'), ('#11', 'Duration'), ('#12', 'Working Hours'), ('#13', 'First Day of Work'), ('#14', 'Insurance'), ('#15', 'Accommodation'), ('#16', 'Basic Living Cost')], max_length=128, null=True),
        ),
    ]
