# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-30 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20180813_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='timestamp',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_in_progress',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_open',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
