# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_complaint_complaint_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Accomodation', 'Accomodation'), ('Job Description', 'Job Description'), ('Other', 'Other')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='host_lc',
            field=models.CharField(choices=[('6TH OCTOBER', '6TH OCTOBER'), ('AAST Alexandria', 'AAST Alexandria'), ('AAST In CAIRO', 'AAST In CAIRO'), ('Ain Shams University', 'Ain Shams University'), ('Alexandria', 'Alexandria'), ('Assiut', 'Assiut'), ('Beni Suef', 'Beni Suef'), ('Cairo University', 'Cairo University'), ('Damietta', 'Damietta'), ('Fayoum', 'Fayoum'), ('GUC', 'GUC'), ('Helwan', 'Helwan'), ('Luxor & Aswan', 'Luxor & Aswan'), ('Mansoura', 'Mansoura'), ('Menofia', 'Menofia'), ('Minya', 'Minya'), ('MIU', 'MIU'), ('New Cairo', 'New Cairo'), ('Sohag', 'Sohag'), ('Suez', 'Suez'), ('Tanta', 'Tanta'), ('Zagazig', 'Zagazig')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='program',
            field=models.CharField(choices=[('GV', 'Global Volunteer'), ('GE', 'Global Entrepreneur'), ('GT', 'Global Talent')], max_length=128, null=True),
        ),
    ]
