# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-21 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20180420_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=128)),
                ('office_id', models.IntegerField(blank=True, null=True)),
                ('office_contact_name', models.CharField(blank=True, max_length=128, null=True)),
                ('office_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_contact_phone', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ep',
            name='ep_host_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Office'),
        ),
        migrations.AlterField(
            model_name='filler',
            name='filler_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Office'),
        ),
        migrations.DeleteModel(
            name='Offices',
        ),
    ]
