# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20180422_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='office_contact_email',
        ),
        migrations.RemoveField(
            model_name='office',
            name='office_contact_name',
        ),
        migrations.RemoveField(
            model_name='office',
            name='office_contact_phone',
        ),
        migrations.RemoveField(
            model_name='office',
            name='office_id',
        ),
    ]
