# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-30 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20180830_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_state',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Complaint', 'Complaint'), ('Request', 'Request'), ('Case', 'Case')], max_length=128, null=True),
        ),
    ]
