# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20180225_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Token',
            },
        ),
        migrations.AlterField(
            model_name='complaint',
            name='host_lc',
            field=models.CharField(choices=[(1489, 'New Cairo'), (1727, 'Menofia'), (1729, 'Assiut'), (2126, 'Beni Suef'), (2114, 'Luxor & Aswan'), (1730, 'Sohag'), (2124, 'Helwan'), (15, 'Suez'), (171, 'Mansoura'), (257, 'GUC'), (1726, 'Fayoum'), (1322, 'AAST In CAIRO'), (109, 'Damietta'), (152, '6TH OCTOBER'), (1788, 'AAST Alexandria'), (899, 'Alexandria'), (1789, 'Ain Shams University'), (2125, 'MIU'), (1114, 'Zagazig'), (1064, 'Cairo University'), (1728, 'Minya'), (2387, 'MC Egypt'), (1725, 'Tanta')], max_length=128, null=True),
        ),
    ]
