# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20180422_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='id',
        ),
        migrations.AddField(
            model_name='office',
            name='office_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='office_contact_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='office_contact_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='office_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
