# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-03 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20180903_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='case_result',
            field=models.FileField(blank=True, null=True, upload_to='uploads/process_files/%Y/%M/%D/case_result'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='uploads/process_files/%Y/%M/%D/invoice'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='oca_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/process_files/%Y/%M/%D/oca'),
        ),
    ]
