# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-03 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import illuminate.forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20180903_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='case_result',
            field=models.FileField(blank=True, null=True, upload_to=illuminate.forms.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=illuminate.forms.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='oca_file',
            field=models.FileField(blank=True, null=True, upload_to=illuminate.forms.models.path_and_rename),
        ),
    ]
