# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20180422_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='office_contact_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='office_contact_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='office_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
