# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-03 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20180903_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='request_state',
            new_name='request_confirmation',
        ),
    ]
