# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20180422_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='standards',
        ),
        migrations.AddField(
            model_name='ticket',
            name='standards',
            field=models.ManyToManyField(blank=True, null=True, to='forms.Standard'),
        ),
    ]
