# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-03 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20180903_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EGP', 'EGP'), ('EUR', 'EUR')], max_length=128, null=True),
        ),
    ]
