# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20180422_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_state',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=128, null=True),
        ),
    ]
