# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-25 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20180520_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='complaint',
            field=models.TextField(blank=True, help_text='Detailed yet to the point for us to help you best!', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='complaint_tag',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Accomodation', 'Accomodation'), ('Job Description', 'Job Description'), ('Other', 'Other')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='program',
            field=models.CharField(blank=True, choices=[('1', 'Global Volunteer'), ('2', 'Global Talent'), ('5', 'Global Entrepreneur')], max_length=1, null=True),
        ),
    ]
