# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-25 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20180525_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='case_brief',
            field=models.TextField(blank=True, help_text='Detailed yet to the point', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='case_mail_subject',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='complaint_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='request_Reason',
            field=models.TextField(blank=True, help_text='Detailed yet to the point for us to help you best!', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requested_break',
            field=models.CharField(blank=True, choices=[('Approval', 'Approval'), ('Realization', 'Realization')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_state',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=128, null=True),
        ),
    ]
