# Generated by Django 2.0 on 2018-06-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_ticket_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Office',
            new_name='office',
        ),
    ]
