# Generated by Django 2.0 on 2018-06-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_auto_20180605_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(max_length=128),
        ),
    ]
