# Generated by Django 2.0 on 2018-06-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_auto_20180607_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
