# Generated by Django 2.0 on 2018-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20180607_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
