# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter Your Full Name.', max_length=128)),
                ('lc', models.CharField(choices=[('6TH OCTOBER', '6TH OCTOBER'), ('AAST Alexandria', 'AAST Alexandria'), ('AAST In CAIRO', 'AAST In CAIRO'), ('Ain Shams University', 'Ain Shams University'), ('Alexandria', 'Alexandria'), ('Assiut', 'Assiut'), ('Beni Suef', 'Beni Suef'), ('Cairo University', 'Cairo University'), ('Damietta', 'Damietta'), ('Fayoum', 'Fayoum'), ('GUC', 'GUC'), ('Helwan', 'Helwan'), ('Luxor & Aswan', 'Luxor & Aswan'), ('Mansoura', 'Mansoura'), ('Menofia', 'Menofia'), ('Minya', 'Minya'), ('MIU', 'MIU'), ('New Cairo', 'New Cairo'), ('Sohag', 'Sohag'), ('Suez', 'Suez'), ('Tanta', 'Tanta'), ('Zagazig', 'Zagazig')], max_length=1, null=True)),
                ('position', models.CharField(choices=[('MCP', 'MCP'), ('MCVP', 'MCVP'), ('LCP', 'LCP'), ('LCVP', 'LCVP'), ('Team Leader', 'Team Leader'), ('Coordinator', 'Coordinator'), ('Member', 'Member')], max_length=1, null=True)),
                ('role', models.CharField(blank=True, choices=[('IGV', 'IGV'), ('IGE', 'IGE'), ('IGT', 'IGT'), ('OGV', 'OGV'), ('OGE', 'OGE'), ('OGT', 'OGT'), ('F&L', 'F&L'), ('TM', 'TM'), ('Marketing', 'Marketing')], max_length=1, null=True)),
                ('ep_name', models.CharField(help_text="Enter EP's Full Name.", max_length=128)),
                ('ep_entity', django_countries.fields.CountryField(max_length=2, null=True)),
                ('ep_email', models.EmailField(max_length=254)),
                ('ep_lc', models.CharField(choices=[('6TH OCTOBER', '6TH OCTOBER'), ('AAST Alexandria', 'AAST Alexandria'), ('AAST In CAIRO', 'AAST In CAIRO'), ('Ain Shams University', 'Ain Shams University'), ('Alexandria', 'Alexandria'), ('Assiut', 'Assiut'), ('Beni Suef', 'Beni Suef'), ('Cairo University', 'Cairo University'), ('Damietta', 'Damietta'), ('Fayoum', 'Fayoum'), ('GUC', 'GUC'), ('Helwan', 'Helwan'), ('Luxor & Aswan', 'Luxor & Aswan'), ('Mansoura', 'Mansoura'), ('Menofia', 'Menofia'), ('Minya', 'Minya'), ('MIU', 'MIU'), ('New Cairo', 'New Cairo'), ('Sohag', 'Sohag'), ('Suez', 'Suez'), ('Tanta', 'Tanta'), ('Zagazig', 'Zagazig')], max_length=1, null=True)),
                ('ep_id', models.IntegerField(help_text='Enter EP ID.')),
                ('opp_id', models.IntegerField(help_text='Enter Opportunity ID.')),
                ('requested_break', models.CharField(choices=[('Approval', 'Approval'), ('Realization', 'Realization')], max_length=1, null=True)),
                ('program', models.CharField(choices=[('GV', 'Global Volunteer'), ('GE', 'Global Entrepreneur'), ('GT', 'Global Talent')], max_length=1, null=True)),
                ('request_Reason', models.TextField(help_text='Detailed yet to the point for us to help you best!')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
